import { User, Signalement, Categorie } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    nom: 'Jean Dupont',
    email: 'jean.dupont@ville.fr',
    role: 'agent',
  },
  {
    id: '2',
    nom: 'Marie Martin',
    email: 'marie.martin@ville.fr',
    role: 'agent',
  },
  {
    id: '3',
    nom: 'Pierre Durand',
    email: 'pierre.durand@ville.fr',
    role: 'responsable',
  },
  {
    id: '4',
    nom: 'Sophie Bernard',
    email: 'sophie.bernard@ville.fr',
    role: 'admin',
  },
];

export const mockCategories: Categorie[] = [
  {
    id: '1',
    nom: 'Voirie',
    description: 'Problèmes de chaussée, trottoirs, signalisation',
    couleur: '#ef4444',
  },
  {
    id: '2',
    nom: 'Éclairage public',
    description: 'Lampadaires défaillants, zones sombres',
    couleur: '#f59e0b',
  },
  {
    id: '3',
    nom: 'Espaces verts',
    description: 'Parcs, jardins, arbres',
    couleur: '#22c55e',
  },
  {
    id: '4',
    nom: 'Propreté',
    description: 'Dépôts sauvages, poubelles, graffitis',
    couleur: '#3b82f6',
  },
  {
    id: '5',
    nom: 'Mobilier urbain',
    description: 'Bancs, abribus, panneaux',
    couleur: '#8b5cf6',
  },
];

export const mockSignalements: Signalement[] = [
  {
    id: '1',
    titre: 'Nid de poule rue de la Mairie',
    description: 'Un nid de poule important s\'est formé devant le n°15 rue de la Mairie. Dangereux pour les vélos et piétons.',
    categorie: 'Voirie',
    statut: 'en_cours',
    priorite: 'haute',
    localisation: '15 rue de la Mairie',
    photos: ['/placeholder-photo.jpg'],
    cree_par: mockUsers[0],
    assigne_a: mockUsers[1],
    date_creation: '2024-01-15T09:30:00',
    date_modification: '2024-01-16T14:20:00',
    historique: [
      {
        id: 'h1',
        date: '2024-01-15T09:30:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Jean Dupont',
      },
      {
        id: 'h2',
        date: '2024-01-15T10:00:00',
        type: 'affectation',
        description: 'Affecté à Marie Martin',
        auteur: 'Pierre Durand',
      },
      {
        id: 'h3',
        date: '2024-01-16T14:20:00',
        type: 'statut',
        description: 'Statut changé vers "En cours"',
        auteur: 'Marie Martin',
      },
    ],
    commentaires: [
      {
        id: 'c1',
        signalement_id: '1',
        auteur: mockUsers[1],
        contenu: 'Intervention prévue demain matin.',
        date: '2024-01-16T14:25:00',
      },
    ],
  },
  {
    id: '2',
    titre: 'Lampadaire éteint Place du Marché',
    description: 'Le lampadaire situé à l\'angle nord-est de la Place du Marché ne fonctionne plus depuis 3 jours.',
    categorie: 'Éclairage public',
    statut: 'nouveau',
    priorite: 'normale',
    localisation: 'Place du Marché - angle nord-est',
    photos: [],
    cree_par: mockUsers[0],
    assigne_a: null,
    date_creation: '2024-01-17T11:00:00',
    date_modification: '2024-01-17T11:00:00',
    historique: [
      {
        id: 'h4',
        date: '2024-01-17T11:00:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Jean Dupont',
      },
    ],
    commentaires: [],
  },
  {
    id: '3',
    titre: 'Branche cassée Parc Central',
    description: 'Une grosse branche est tombée et bloque partiellement l\'allée principale du parc.',
    categorie: 'Espaces verts',
    statut: 'resolu',
    priorite: 'haute',
    localisation: 'Parc Central - allée principale',
    photos: ['/placeholder-photo.jpg'],
    cree_par: mockUsers[1],
    assigne_a: mockUsers[0],
    date_creation: '2024-01-10T08:00:00',
    date_modification: '2024-01-11T16:00:00',
    historique: [
      {
        id: 'h5',
        date: '2024-01-10T08:00:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Marie Martin',
      },
      {
        id: 'h6',
        date: '2024-01-10T09:00:00',
        type: 'affectation',
        description: 'Affecté à Jean Dupont',
        auteur: 'Pierre Durand',
      },
      {
        id: 'h7',
        date: '2024-01-11T16:00:00',
        type: 'statut',
        description: 'Statut changé vers "Résolu"',
        auteur: 'Jean Dupont',
      },
    ],
    commentaires: [
      {
        id: 'c2',
        signalement_id: '3',
        auteur: mockUsers[0],
        contenu: 'Branche dégagée et évacuée.',
        date: '2024-01-11T16:00:00',
      },
    ],
  },
  {
    id: '4',
    titre: 'Dépôt sauvage rue des Lilas',
    description: 'Des encombrants ont été abandonnés sur le trottoir devant le n°8.',
    categorie: 'Propreté',
    statut: 'bloque',
    priorite: 'normale',
    localisation: '8 rue des Lilas',
    photos: ['/placeholder-photo.jpg'],
    cree_par: mockUsers[2],
    assigne_a: mockUsers[0],
    date_creation: '2024-01-14T14:30:00',
    date_modification: '2024-01-16T09:00:00',
    historique: [
      {
        id: 'h8',
        date: '2024-01-14T14:30:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Pierre Durand',
      },
      {
        id: 'h9',
        date: '2024-01-15T08:00:00',
        type: 'affectation',
        description: 'Affecté à Jean Dupont',
        auteur: 'Pierre Durand',
      },
      {
        id: 'h10',
        date: '2024-01-16T09:00:00',
        type: 'statut',
        description: 'Statut changé vers "Bloqué"',
        auteur: 'Jean Dupont',
      },
    ],
    commentaires: [
      {
        id: 'c3',
        signalement_id: '4',
        auteur: mockUsers[0],
        contenu: 'En attente du véhicule de collecte, indisponible cette semaine.',
        date: '2024-01-16T09:05:00',
      },
    ],
  },
  {
    id: '5',
    titre: 'Banc cassé Square Gambetta',
    description: 'Un des bancs du square a une latte cassée, risque de blessure.',
    categorie: 'Mobilier urbain',
    statut: 'nouveau',
    priorite: 'basse',
    localisation: 'Square Gambetta',
    photos: [],
    cree_par: mockUsers[1],
    assigne_a: null,
    date_creation: '2024-01-18T10:15:00',
    date_modification: '2024-01-18T10:15:00',
    historique: [
      {
        id: 'h11',
        date: '2024-01-18T10:15:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Marie Martin',
      },
    ],
    commentaires: [],
  },
  {
    id: '6',
    titre: 'Graffitis sur l\'abribus Gare',
    description: 'Tags importants sur les vitres et parois de l\'abribus devant la gare.',
    categorie: 'Propreté',
    statut: 'en_cours',
    priorite: 'basse',
    localisation: 'Abribus - Place de la Gare',
    photos: ['/placeholder-photo.jpg'],
    cree_par: mockUsers[0],
    assigne_a: mockUsers[1],
    date_creation: '2024-01-12T16:00:00',
    date_modification: '2024-01-17T11:30:00',
    historique: [
      {
        id: 'h12',
        date: '2024-01-12T16:00:00',
        type: 'creation',
        description: 'Signalement créé',
        auteur: 'Jean Dupont',
      },
      {
        id: 'h13',
        date: '2024-01-17T11:30:00',
        type: 'statut',
        description: 'Statut changé vers "En cours"',
        auteur: 'Marie Martin',
      },
    ],
    commentaires: [],
  },
];
